-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 21:06:49 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bibliotecla2024
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bibliotecla2024
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bibliotecla2024` DEFAULT CHARACTER SET utf8 ;
USE `bibliotecla2024` ;

-- -----------------------------------------------------
-- Table `bibliotecla2024`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecla2024`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `cp` VARCHAR(8) NOT NULL,
  `fone` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecla2024`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecla2024`.`autores` (
  `idautores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idautores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecla2024`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecla2024`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecla2024`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecla2024`.`livro` (
  `idlivro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `autores_idautores` INT NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idlivro`),
  INDEX `fk_livro_autores1_idx` (`autores_idautores` ASC) ,
  INDEX `fk_livro_categorias1_idx` (`categorias_idcategorias` ASC) ,
  CONSTRAINT `fk_livro_autores1`
    FOREIGN KEY (`autores_idautores`)
    REFERENCES `bibliotecla2024`.`autores` (`idautores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `bibliotecla2024`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bibliotecla2024`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bibliotecla2024`.`emprestimo` (
  `idemprestimo` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `livro_idlivro` INT NOT NULL,
  `dtemprestimo` DATE NOT NULL,
  `dtentrega` DATE NULL,
  INDEX `fk_usuario_has_livro_livro1_idx` (`livro_idlivro` ASC) ,
  INDEX `fk_usuario_has_livro_usuario_idx` (`usuario_idusuario` ASC) ,
  PRIMARY KEY (`idemprestimo`),
  CONSTRAINT `fk_usuario_has_livro_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bibliotecla2024`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_livro_livro1`
    FOREIGN KEY (`livro_idlivro`)
    REFERENCES `bibliotecla2024`.`livro` (`idlivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
